dist: trusty
sudo: false
language: cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc
      - make
      - cmake
      - gdb

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2
#  - ./configure --enable-gcov && make && make check
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
