#dist: trusty
sudo: false
language: cpp


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc
      - make
      - cmake
      - gdb

before_install:
  - pip install --user cpp-coveralls

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake .
  - cmake --build . -- -j2
  - ./configure --enable-gcov && make && make check
  - ctest
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false